import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { AppSidebar } from "./components/app-sidebar";
import { SidebarProvider, SidebarTrigger } from "@/components/ui/sidebar";
import { ThemeProvider } from "./components/theme-provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
  //   
  //   <AppSidebar />
  //   <main>
  //     
  //     {children}
  //   </main>
  // </SidebarProvider>

    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
        attribute="class"
        defaultTheme="system"
        enableSystem
        disableTransitionOnChange
        >
        <div className="flex min-h-screen">
          {/* Sidebar */}
          <SidebarProvider>
          <AppSidebar />

          {/* Main Content */}
          <main className="flex-1 p-4">
          <SidebarTrigger />
            {children}
            </main>
          </SidebarProvider>
        </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
